<a href="https://colab.research.google.com/github/LGM429/hw-pp-2024/blob/main/NY_bridge_data_2014_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
from bs4 import BeautifulSoup

In [6]:

import requests
import glob

In [7]:
base_url = "https://www.fhwa.dot.gov/bridge/nbi/20"
year_l = [2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024]

In [8]:
smart_years = '04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24'

In [9]:
len(smart_years)

21

In [10]:
end_url = "/delimited/NY"

In [11]:
urls = []
for year in smart_years:
  url = (f'{base_url}{year}{end_url}{year}.txt')
  urls.append(url)

urls

['https://www.fhwa.dot.gov/bridge/nbi/2004/delimited/NY04.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2005/delimited/NY05.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2006/delimited/NY06.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2007/delimited/NY07.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2008/delimited/NY08.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2009/delimited/NY09.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2010/delimited/NY10.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2011/delimited/NY11.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2012/delimited/NY12.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2013/delimited/NY13.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2014/delimited/NY14.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2015/delimited/NY15.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2016/delimited/NY16.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2017/delimited/NY17.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2018/delimited/NY18.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2019/delimited/NY19.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2020/delimited/NY20.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2021/delimited/NY21.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2022/delimited/NY22.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2023/delimited/NY23.txt',
 'https://www.fhwa.dot.gov/bridge/nbi/2024/delimited/NY24.txt']

In [15]:
txt_all = []
for url in urls:
  !wget {url}

--2024-12-10 14:41:08--  https://www.fhwa.dot.gov/bridge/nbi/2004/delimited/NY04.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9249065 (8.8M) [text/plain]
Saving to: ‘NY04.txt’

NY04.txt            100%[===================>]   8.82M  15.9MB/s    in 0.6s

2024-12-10 14:41:09 (15.9 MB/s) - ‘NY04.txt’ saved [9249065/9249065]

--2024-12-10 14:41:09--  https://www.fhwa.dot.gov/bridge/nbi/2005/delimited/NY05.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9474621 (9.0M) [text/plain]
Saving to: ‘NY05.txt’

NY05.txt            100%[===================>]   9.04M  15.3MB/s    in 0.6s

2024-12-10 14:41:10 (15.3 MB/s) - ‘NY05.txt’ saved [9474621/9474621]

--2024-12-10 14:41:10--  https://www.fhwa.dot.gov/bridge/nbi/2006/delimited/NY06.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9462161 (9.0M) [text/plain]
Saving to: ‘NY06.txt’

NY06.txt            100%[===================>]   9.02M  14.8MB/s    in 0.6s

2024-12-10 14:41:11 (14.8 MB/s) - ‘NY06.txt’ saved [9462161/9462161]

--2024-12-10 14:41:11--  https://www.fhwa.dot.gov/bridge/nbi/2007/delimited/NY07.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9635440 (9.2M) [text/plain]
Saving to: ‘NY07.txt’

NY07.txt            100%[===================>]   9.19M  14.2MB/s    in 0.6s

2024-12-10 14:41:12 (14.2 MB/s) - ‘NY07.txt’ saved [9635440/9635440]

--2024-12-10 14:41:12--  https://www.fhwa.dot.gov/bridge/nbi/2008/delimited/NY08.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9637176 (9.2M) [text/plain]
Saving to: ‘NY08.txt’

NY08.txt            100%[===================>]   9.19M  15.6MB/s    in 0.6s

2024-12-10 14:41:13 (15.6 MB/s) - ‘NY08.txt’ saved [9637176/9637176]

--2024-12-10 14:41:13--  https://www.fhwa.dot.gov/bridge/nbi/2009/delimited/NY09.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9564446 (9.1M) [text/plain]
Saving to: ‘NY09.txt’

NY09.txt            100%[===================>]   9.12M  15.4MB/s    in 0.6s

2024-12-10 14:41:14 (15.4 MB/s) - ‘NY09.txt’ saved [9564446/9564446]

--2024-12-10 14:41:14--  https://www.fhwa.dot.gov/bridge/nbi/2010/delimited/NY10.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7962518 (7.6M) [text/plain]
Saving to: ‘NY10.txt’

NY10.txt            100%[===================>]   7.59M  12.5MB/s    in 0.6s

2024-12-10 14:41:15 (12.5 MB/s) - ‘NY10.txt’ saved [7962518/7962518]

--2024-12-10 14:41:15--  https://www.fhwa.dot.gov/bridge/nbi/2011/delimited/NY11.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7931788 (7.6M) [text/plain]
Saving to: ‘NY11.txt’

NY11.txt            100%[===================>]   7.56M  11.0MB/s    in 0.7s

2024-12-10 14:41:16 (11.0 MB/s) - ‘NY11.txt’ saved [7931788/7931788]

--2024-12-10 14:41:16--  https://www.fhwa.dot.gov/bridge/nbi/2012/delimited/NY12.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8032522 (7.7M) [text/plain]
Saving to: ‘NY12.txt’

NY12.txt            100%[===================>]   7.66M  13.7MB/s    in 0.6s

2024-12-10 14:41:17 (13.7 MB/s) - ‘NY12.txt’ saved [8032522/8032522]

--2024-12-10 14:41:17--  https://www.fhwa.dot.gov/bridge/nbi/2013/delimited/NY13.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8461498 (8.1M) [text/plain]
Saving to: ‘NY13.txt’

NY13.txt            100%[===================>]   8.07M  13.5MB/s    in 0.6s

2024-12-10 14:41:18 (13.5 MB/s) - ‘NY13.txt’ saved [8461498/8461498]

--2024-12-10 14:41:18--  https://www.fhwa.dot.gov/bridge/nbi/2014/delimited/NY14.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8486412 (8.1M) [text/plain]
Saving to: ‘NY14.txt’

NY14.txt            100%[===================>]   8.09M  12.8MB/s    in 0.6s

2024-12-10 14:41:19 (12.8 MB/s) - ‘NY14.txt’ saved [8486412/8486412]

--2024-12-10 14:41:19--  https://www.fhwa.dot.gov/bridge/nbi/2015/delimited/NY15.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8035168 (7.7M) [text/plain]
Saving to: ‘NY15.txt’

NY15.txt            100%[===================>]   7.66M  13.7MB/s    in 0.6s

2024-12-10 14:41:19 (13.7 MB/s) - ‘NY15.txt’ saved [8035168/8035168]

--2024-12-10 14:41:20--  https://www.fhwa.dot.gov/bridge/nbi/2016/delimited/NY16.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8038929 (7.7M) [text/plain]
Saving to: ‘NY16.txt’

NY16.txt            100%[===================>]   7.67M  12.4MB/s    in 0.6s

2024-12-10 14:41:20 (12.4 MB/s) - ‘NY16.txt’ saved [8038929/8038929]

--2024-12-10 14:41:21--  https://www.fhwa.dot.gov/bridge/nbi/2017/delimited/NY17.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8196107 (7.8M) [text/plain]
Saving to: ‘NY17.txt’

NY17.txt            100%[===================>]   7.82M  14.0MB/s    in 0.6s

2024-12-10 14:41:21 (14.0 MB/s) - ‘NY17.txt’ saved [8196107/8196107]

--2024-12-10 14:41:21--  https://www.fhwa.dot.gov/bridge/nbi/2018/delimited/NY18.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8227525 (7.8M) [text/plain]
Saving to: ‘NY18.txt’

NY18.txt            100%[===================>]   7.85M  13.2MB/s    in 0.6s

2024-12-10 14:41:22 (13.2 MB/s) - ‘NY18.txt’ saved [8227525/8227525]

--2024-12-10 14:41:22--  https://www.fhwa.dot.gov/bridge/nbi/2019/delimited/NY19.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7533512 (7.2M) [text/plain]
Saving to: ‘NY19.txt’

NY19.txt            100%[===================>]   7.18M  12.1MB/s    in 0.6s

2024-12-10 14:41:23 (12.1 MB/s) - ‘NY19.txt’ saved [7533512/7533512]

--2024-12-10 14:41:23--  https://www.fhwa.dot.gov/bridge/nbi/2020/delimited/NY20.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7542334 (7.2M) [text/plain]
Saving to: ‘NY20.txt’

NY20.txt            100%[===================>]   7.19M  12.3MB/s    in 0.6s

2024-12-10 14:41:24 (12.3 MB/s) - ‘NY20.txt’ saved [7542334/7542334]

--2024-12-10 14:41:24--  https://www.fhwa.dot.gov/bridge/nbi/2021/delimited/NY21.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7551528 (7.2M) [text/plain]
Saving to: ‘NY21.txt’

NY21.txt            100%[===================>]   7.20M  11.0MB/s    in 0.7s

2024-12-10 14:41:25 (11.0 MB/s) - ‘NY21.txt’ saved [7551528/7551528]

--2024-12-10 14:41:25--  https://www.fhwa.dot.gov/bridge/nbi/2022/delimited/NY22.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7555509 (7.2M) [text/plain]
Saving to: ‘NY22.txt’

NY22.txt            100%[===================>]   7.21M  11.8MB/s    in 0.6s

2024-12-10 14:41:26 (11.8 MB/s) - ‘NY22.txt’ saved [7555509/7555509]

--2024-12-10 14:41:26--  https://www.fhwa.dot.gov/bridge/nbi/2023/delimited/NY23.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7568627 (7.2M) [text/plain]
Saving to: ‘NY23.txt’

NY23.txt            100%[===================>]   7.22M  13.0MB/s    in 0.6s

2024-12-10 14:41:27 (13.0 MB/s) - ‘NY23.txt’ saved [7568627/7568627]

--2024-12-10 14:41:27--  https://www.fhwa.dot.gov/bridge/nbi/2024/delimited/NY24.txt
Resolving www.fhwa.dot.gov (www.fhwa.dot.gov)... 204.68.194.17
Connecting to www.fhwa.dot.gov (www.fhwa.dot.gov)|204.68.194.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7427451 (7.1M) [text/plain]
Saving to: ‘NY24.txt’

NY24.txt            100%[===================>]   7.08M  12.8MB/s    in 0.6s

2024-12-10 14:41:28 (12.8 MB/s) - ‘NY24.txt’ saved [7427451/7427451]

In [19]:
ny_files = glob.glob("NY*")

In [20]:
ny_files

['NY14.txt',
 'NY19.txt',
 'NY11.txt',
 'NY18.txt',
 'NY22.txt',
 'NY06.txt',
 'NY23.txt',
 'NY13.txt',
 'NY12.txt',
 'NY16.txt',
 'NY09.txt',
 'NY20.txt',
 'NY05.txt',
 'NY08.txt',
 'NY17.txt',
 'NY10.txt',
 'NY04.txt',
 'NY15.txt',
 'NY07.txt',
 'NY21.txt',
 'NY24.txt']

In [92]:
ny_recents = ['NY19.txt','NY20.txt','NY21.txt','NY22.txt','NY23.txt','NY24.txt']

In [93]:
df_fl = []
for file in ny_recents:
  df = pd.read_csv(file, sep=',', header=None)
  df_fl.append(df)

<ipython-input-93-0843d3628a87>:3: DtypeWarning: Columns (0,2,3,4,6,8,9,11,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,32,33,34,35,36,40,42,43,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,62,64,65,71,72,73,74,75,78,80,81,82,83,84,85,89,90,91,92,93,94,95,97,99,101,103,104,105,107,108,110,111,112,115,116,117,119,121,122) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=',', header=None)
<ipython-input-93-0843d3628a87>:3: DtypeWarning: Columns (0,2,3,4,6,8,9,11,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,32,33,34,35,36,40,42,43,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,62,64,65,71,72,73,74,75,78,80,81,82,83,84,85,89,90,91,92,93,94,95,97,99,101,103,104,105,107,108,110,111,112,115,116,117,119,121,122) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=',', header=None)
<ipython-input-93-0843d3628a87>:3: DtypeWarning: Columns (0,2,3,4,6,8,9,11,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,32,33,34,35,36,40,42,43,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,62,64,65,71,72,73,74,75,78,80,81,82,83,84,85,89,90,91,92,93,94,95,97,99,101,103,104,105,107,108,110,111,112,115,116,117,119,121,122) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=',', header=None)
<ipython-input-93-0843d3628a87>:3: DtypeWarning: Columns (0,2,3,4,6,8,9,11,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,32,33,34,35,36,40,42,43,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,62,64,65,71,72,73,74,75,78,80,81,82,83,84,85,89,90,91,92,93,94,95,97,99,101,103,104,105,107,108,110,111,112,115,116,117,119,121,122) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=',', header=None)
<ipython-input-93-0843d3628a87>:3: DtypeWarning: Columns (0,2,3,4,6,8,9,11,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,32,33,34,35,36,40,42,43,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,62,64,65,71,72,73,74,75,78,80,81,82,83,84,85,89,90,91,92,93,94,95,97,99,101,103,104,105,107,108,110,111,112,115,116,117,119,121,122) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=',', header=None)
<ipython-input-93-0843d3628a87>:3: DtypeWarning: Columns (0,2,3,4,6,8,9,11,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,32,33,34,35,36,40,42,43,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,62,64,65,71,72,73,74,75,78,80,81,82,83,84,85,89,90,91,92,93,94,95,97,99,101,103,104,105,107,108,110,111,112,115,116,117,119,121,122) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=',', header=None)

In [94]:
df_all = pd.concat(df_fl)

In [95]:
df_all

,0,1,2,3,4,5,6,7,8,9,...,113,114,115,116,117,118,119,120,121,122
0,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,ROUTE_NUMBER_005D,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,...,BRIDGE_LEN_IND_112,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,FED_AGENCY,SUBMITTED_BY,BRIDGE_CONDITION,LOWEST_RATING,DECK_AREA
1,36,000000001000040,1,2,1,00001,0,87,119,44831,...,Y,5,17873,2038,NaN,N,36,F,5,428.13
2,36,000000001000090,1,2,1,00001,0,87,119,64309,...,Y,N,25696,2038,NaN,N,36,F,5,1522.56
3,36,000000001000121,1,2,1,00001,0,87,119,59223,...,Y,5,15917,2038,NaN,N,36,F,5,454.26
4,36,000000001000122,1,2,1,00001,0,87,119,59223,...,Y,5,15917,2038,NaN,N,36,F,5,426.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17638,36,DAPUSMWPT000015,1,8,0,00000,0,00,71,80747,...,Y,N,200,2044,NaN,Y,74,F,5,110.88
17639,36,DAPUSMWPT000025,1,8,0,00000,0,00,71,80747,...,Y,8,20,2044,NaN,Y,74,P,4,140.4
17640,36,DAPUSMWPT000031,1,8,0,00000,0,00,71,80747,...,Y,8,20,2044,NaN,Y,74,F,6,27.95
17641,36,DAPUSMWPT000036,1,8,0,00000,0,00,71,80747,...,Y,N,500,2044,NaN,Y,74,F,6,1938.75
17642,36,DAPUSMWPT000037,1,8,0,00000,0,00,71,80747,...,Y,3,20,2044,NaN,Y,74,P,4,34.04

In [98]:
df_1

,0,1,2,3,4,5,6,7,8,9,...,113,114,115,116,117,118,119,120,121,122
0,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,ROUTE_NUMBER_005D,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,...,BRIDGE_LEN_IND_112,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,FED_AGENCY,SUBMITTED_BY,BRIDGE_CONDITION,LOWEST_RATING,DECK_AREA
1,36,000000001000040,1,2,1,00001,0,87,119,44831,...,Y,5,17873,2038,NaN,N,36,F,5,428.13
2,36,000000001000090,1,2,1,00001,0,87,119,64309,...,Y,N,25696,2038,NaN,N,36,F,5,1522.56
3,36,000000001000121,1,2,1,00001,0,87,119,59223,...,Y,5,15917,2038,NaN,N,36,F,5,454.26
4,36,000000001000122,1,2,1,00001,0,87,119,59223,...,Y,5,15917,2038,NaN,N,36,F,5,426.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17638,36,DAPUSMWPT000015,1,8,0,00000,0,00,71,80747,...,Y,N,200,2044,NaN,Y,74,F,5,110.88
17639,36,DAPUSMWPT000025,1,8,0,00000,0,00,71,80747,...,Y,8,20,2044,NaN,Y,74,P,4,140.4
17640,36,DAPUSMWPT000031,1,8,0,00000,0,00,71,80747,...,Y,8,20,2044,NaN,Y,74,F,6,27.95
17641,36,DAPUSMWPT000036,1,8,0,00000,0,00,71,80747,...,Y,N,500,2044,NaN,Y,74,F,6,1938.75
17642,36,DAPUSMWPT000037,1,8,0,00000,0,00,71,80747,...,Y,3,20,2044,NaN,Y,74,P,4,34.04

In [55]:
## then do -- only keep in df if the row has one of the correct county codes above (for NYC)

In [107]:
df_1.columns = df_1.iloc[0]

In [108]:
df_1

,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,ROUTE_NUMBER_005D,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,...,BRIDGE_LEN_IND_112,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,FED_AGENCY,SUBMITTED_BY,BRIDGE_CONDITION,LOWEST_RATING,DECK_AREA
0,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,ROUTE_NUMBER_005D,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,...,BRIDGE_LEN_IND_112,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,FED_AGENCY,SUBMITTED_BY,BRIDGE_CONDITION,LOWEST_RATING,DECK_AREA
1,36,000000001000040,1,2,1,00001,0,87,119,44831,...,Y,5,17873,2038,NaN,N,36,F,5,428.13
2,36,000000001000090,1,2,1,00001,0,87,119,64309,...,Y,N,25696,2038,NaN,N,36,F,5,1522.56
3,36,000000001000121,1,2,1,00001,0,87,119,59223,...,Y,5,15917,2038,NaN,N,36,F,5,454.26
4,36,000000001000122,1,2,1,00001,0,87,119,59223,...,Y,5,15917,2038,NaN,N,36,F,5,426.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17638,36,DAPUSMWPT000015,1,8,0,00000,0,00,71,80747,...,Y,N,200,2044,NaN,Y,74,F,5,110.88
17639,36,DAPUSMWPT000025,1,8,0,00000,0,00,71,80747,...,Y,8,20,2044,NaN,Y,74,P,4,140.4
17640,36,DAPUSMWPT000031,1,8,0,00000,0,00,71,80747,...,Y,8,20,2044,NaN,Y,74,F,6,27.95
17641,36,DAPUSMWPT000036,1,8,0,00000,0,00,71,80747,...,Y,N,500,2044,NaN,Y,74,F,6,1938.75
17642,36,DAPUSMWPT000037,1,8,0,00000,0,00,71,80747,...,Y,3,20,2044,NaN,Y,74,P,4,34.04

In [109]:
df_1.drop(index=df_1.index[0], axis=0, inplace=True)

<ipython-input-109-89f1f916020b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1.drop(index=df_1.index[0], axis=0, inplace=True)

In [110]:
df_1

,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,ROUTE_NUMBER_005D,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,...,BRIDGE_LEN_IND_112,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,FED_AGENCY,SUBMITTED_BY,BRIDGE_CONDITION,LOWEST_RATING,DECK_AREA
1,36,000000001000040,1,2,1,00001,0,87,119,44831,...,Y,5,17873,2038,NaN,N,36,F,5,428.13
2,36,000000001000090,1,2,1,00001,0,87,119,64309,...,Y,N,25696,2038,NaN,N,36,F,5,1522.56
3,36,000000001000121,1,2,1,00001,0,87,119,59223,...,Y,5,15917,2038,NaN,N,36,F,5,454.26
4,36,000000001000122,1,2,1,00001,0,87,119,59223,...,Y,5,15917,2038,NaN,N,36,F,5,426.24
5,36,000000001000140,1,3,1,00032,0,11,001,46536,...,Y,N,8237,2038,NaN,N,36,F,6,524.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17638,36,DAPUSMWPT000015,1,8,0,00000,0,00,71,80747,...,Y,N,200,2044,NaN,Y,74,F,5,110.88
17639,36,DAPUSMWPT000025,1,8,0,00000,0,00,71,80747,...,Y,8,20,2044,NaN,Y,74,P,4,140.4
17640,36,DAPUSMWPT000031,1,8,0,00000,0,00,71,80747,...,Y,8,20,2044,NaN,Y,74,F,6,27.95
17641,36,DAPUSMWPT000036,1,8,0,00000,0,00,71,80747,...,Y,N,500,2044,NaN,Y,74,F,6,1938.75
17642,36,DAPUSMWPT000037,1,8,0,00000,0,00,71,80747,...,Y,3,20,2044,NaN,Y,74,P,4,34.04

In [111]:
df_1

,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,ROUTE_NUMBER_005D,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,...,BRIDGE_LEN_IND_112,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,FED_AGENCY,SUBMITTED_BY,BRIDGE_CONDITION,LOWEST_RATING,DECK_AREA
1,36,000000001000040,1,2,1,00001,0,87,119,44831,...,Y,5,17873,2038,NaN,N,36,F,5,428.13
2,36,000000001000090,1,2,1,00001,0,87,119,64309,...,Y,N,25696,2038,NaN,N,36,F,5,1522.56
3,36,000000001000121,1,2,1,00001,0,87,119,59223,...,Y,5,15917,2038,NaN,N,36,F,5,454.26
4,36,000000001000122,1,2,1,00001,0,87,119,59223,...,Y,5,15917,2038,NaN,N,36,F,5,426.24
5,36,000000001000140,1,3,1,00032,0,11,001,46536,...,Y,N,8237,2038,NaN,N,36,F,6,524.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17638,36,DAPUSMWPT000015,1,8,0,00000,0,00,71,80747,...,Y,N,200,2044,NaN,Y,74,F,5,110.88
17639,36,DAPUSMWPT000025,1,8,0,00000,0,00,71,80747,...,Y,8,20,2044,NaN,Y,74,P,4,140.4
17640,36,DAPUSMWPT000031,1,8,0,00000,0,00,71,80747,...,Y,8,20,2044,NaN,Y,74,F,6,27.95
17641,36,DAPUSMWPT000036,1,8,0,00000,0,00,71,80747,...,Y,N,500,2044,NaN,Y,74,F,6,1938.75
17642,36,DAPUSMWPT000037,1,8,0,00000,0,00,71,80747,...,Y,3,20,2044,NaN,Y,74,P,4,34.04

In [114]:
df_1["COUNTY_CODE_003"].value_counts()

COUNTY_CODE_003
29     3037
119    2943
101    2587
055    2342
029    2317
       ...
117     210
053     168
099     120
123     114
061     113
Name: count, Length: 124, dtype: int64

In [116]:
ny_county_codes = [85,81,47,61,5,"085","081","047","061","005"]

In [145]:
df_2 = df_1[df_1["COUNTY_CODE_003"].isin(ny_county_codes)]
df_2

,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,ROUTE_NUMBER_005D,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,...,BRIDGE_LEN_IND_112,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,FED_AGENCY,SUBMITTED_BY,BRIDGE_CONDITION,LOWEST_RATING,DECK_AREA
4367,36,000000001055009,1,1,1,00495,0,N4,081,51000,...,Y,N,118735,2038,NaN,N,36,P,4,36434.3
4368,36,000000001055019,1,1,1,00495,0,N4,081,51000,...,Y,N,236498,2038,NaN,N,36,G,7,1988
4369,36,000000001055040,1,5,1,0907P,0,N3,061,51000,...,Y,3,93862,2038,NaN,N,36,F,5,2984.96
4370,36,000000001055070,1,8,0,00000,0,N4,081,51000,...,Y,N,0,0,NaN,N,36,F,5,3471.3
4371,36,000000001055089,1,1,1,00495,0,N4,081,51000,...,Y,8,147640,2038,NaN,N,36,F,5,4155.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17506,36,000000005525280,1,8,7,00000,0,N4,81,51000,...,Y,N,0,0,NaN,N,36,G,9,902.06
17507,36,000000005525290,1,8,8,00000,0,N4,81,51000,...,Y,N,0,0,NaN,N,36,G,9,3740.72
17508,36,000000005525291,1,8,7,00000,0,N4,81,51000,...,Y,N,0,0,NaN,N,36,G,9,1657.6
17509,36,000000005525292,1,8,8,00000,0,N4,81,51000,...,Y,N,0,0,NaN,N,36,G,9,4616.64
17582,36,000000007702320,1,5,0,00000,0,N1,5,51000,...,Y,N,70,2041,NaN,N,36,P,4,232.36

In [146]:
print(*df_2.columns)

STATE_CODE_001 STRUCTURE_NUMBER_008 RECORD_TYPE_005A ROUTE_PREFIX_005B SERVICE_LEVEL_005C ROUTE_NUMBER_005D DIRECTION_005E HIGHWAY_DISTRICT_002 COUNTY_CODE_003 PLACE_CODE_004 FEATURES_DESC_006A CRITICAL_FACILITY_006B FACILITY_CARRIED_007 LOCATION_009 MIN_VERT_CLR_010 KILOPOINT_011 BASE_HWY_NETWORK_012 LRS_INV_ROUTE_013A SUBROUTE_NO_013B LAT_016 LONG_017 DETOUR_KILOS_019 TOLL_020 MAINTENANCE_021 OWNER_022 FUNCTIONAL_CLASS_026 YEAR_BUILT_027 TRAFFIC_LANES_ON_028A TRAFFIC_LANES_UND_028B ADT_029 YEAR_ADT_030 DESIGN_LOAD_031 APPR_WIDTH_MT_032 MEDIAN_CODE_033 DEGREES_SKEW_034 STRUCTURE_FLARED_035 RAILINGS_036A TRANSITIONS_036B APPR_RAIL_036C APPR_RAIL_END_036D HISTORY_037 NAVIGATION_038 NAV_VERT_CLR_MT_039 NAV_HORR_CLR_MT_040 OPEN_CLOSED_POSTED_041 SERVICE_ON_042A SERVICE_UND_042B STRUCTURE_KIND_043A STRUCTURE_TYPE_043B APPR_KIND_044A APPR_TYPE_044B MAIN_UNIT_SPANS_045 APPR_SPANS_046 HORR_CLR_MT_047 MAX_SPAN_LEN_MT_048 STRUCTURE_LEN_MT_049 LEFT_CURB_MT_050A RIGHT_CURB_MT_050B ROADWAY_WIDTH_MT_051 DECK_WIDTH_MT_052 VERT_CLR_OVER_MT_053 VERT_CLR_UND_REF_054A VERT_CLR_UND_054B LAT_UND_REF_055A LAT_UND_MT_055B LEFT_LAT_UND_MT_056 DECK_COND_058 SUPERSTRUCTURE_COND_059 SUBSTRUCTURE_COND_060 CHANNEL_COND_061 CULVERT_COND_062 OPR_RATING_METH_063 OPERATING_RATING_064 INV_RATING_METH_065 INVENTORY_RATING_066 STRUCTURAL_EVAL_067 DECK_GEOMETRY_EVAL_068 UNDCLRENCE_EVAL_069 POSTING_EVAL_070 WATERWAY_EVAL_071 APPR_ROAD_EVAL_072 WORK_PROPOSED_075A WORK_DONE_BY_075B IMP_LEN_MT_076 DATE_OF_INSPECT_090 INSPECT_FREQ_MONTHS_091 FRACTURE_092A UNDWATER_LOOK_SEE_092B SPEC_INSPECT_092C FRACTURE_LAST_DATE_093A UNDWATER_LAST_DATE_093B SPEC_LAST_DATE_093C BRIDGE_IMP_COST_094 ROADWAY_IMP_COST_095 TOTAL_IMP_COST_096 YEAR_OF_IMP_097 OTHER_STATE_CODE_098A OTHER_STATE_PCNT_098B OTHR_STATE_STRUC_NO_099 STRAHNET_HIGHWAY_100 PARALLEL_STRUCTURE_101 TRAFFIC_DIRECTION_102 TEMP_STRUCTURE_103 HIGHWAY_SYSTEM_104 FEDERAL_LANDS_105 YEAR_RECONSTRUCTED_106 DECK_STRUCTURE_TYPE_107 SURFACE_TYPE_108A MEMBRANE_TYPE_108B DECK_PROTECTION_108C PERCENT_ADT_TRUCK_109 NATIONAL_NETWORK_110 PIER_PROTECTION_111 BRIDGE_LEN_IND_112 SCOUR_CRITICAL_113 FUTURE_ADT_114 YEAR_OF_FUTURE_ADT_115 MIN_NAV_CLR_MT_116 FED_AGENCY SUBMITTED_BY BRIDGE_CONDITION LOWEST_RATING DECK_AREA

In [148]:
df_2["COUNTY_CODE_003"] = df_2["COUNTY_CODE_003"].astype(int)

<ipython-input-148-ce58f729539f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2["COUNTY_CODE_003"] = df_2["COUNTY_CODE_003"].astype(int)

In [147]:
print(df_2["DATE_OF_INSPECT_090"])

4367     1218
4368      617
4369      817
4370      418
4371      418
         ...
17506     822
17507     822
17508     722
17509     822
17582    1223
Name: DATE_OF_INSPECT_090, Length: 8801, dtype: object

In [149]:
df_2

,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,ROUTE_NUMBER_005D,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,...,BRIDGE_LEN_IND_112,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,FED_AGENCY,SUBMITTED_BY,BRIDGE_CONDITION,LOWEST_RATING,DECK_AREA
4367,36,000000001055009,1,1,1,00495,0,N4,81,51000,...,Y,N,118735,2038,NaN,N,36,P,4,36434.3
4368,36,000000001055019,1,1,1,00495,0,N4,81,51000,...,Y,N,236498,2038,NaN,N,36,G,7,1988
4369,36,000000001055040,1,5,1,0907P,0,N3,61,51000,...,Y,3,93862,2038,NaN,N,36,F,5,2984.96
4370,36,000000001055070,1,8,0,00000,0,N4,81,51000,...,Y,N,0,0,NaN,N,36,F,5,3471.3
4371,36,000000001055089,1,1,1,00495,0,N4,81,51000,...,Y,8,147640,2038,NaN,N,36,F,5,4155.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17506,36,000000005525280,1,8,7,00000,0,N4,81,51000,...,Y,N,0,0,NaN,N,36,G,9,902.06
17507,36,000000005525290,1,8,8,00000,0,N4,81,51000,...,Y,N,0,0,NaN,N,36,G,9,3740.72
17508,36,000000005525291,1,8,7,00000,0,N4,81,51000,...,Y,N,0,0,NaN,N,36,G,9,1657.6
17509,36,000000005525292,1,8,8,00000,0,N4,81,51000,...,Y,N,0,0,NaN,N,36,G,9,4616.64
17582,36,000000007702320,1,5,0,00000,0,N1,5,51000,...,Y,N,70,2041,NaN,N,36,P,4,232.36

In [150]:
df_2["COUNTY_CODE_003"].value_counts()

COUNTY_CODE_003
81    3039
5     1866
61    1466
47    1457
85     973
Name: count, dtype: int64

In [174]:
print(df_2["DATE_OF_INSPECT_090"])

4367     1218
4368      617
4369      817
4370      418
4371      418
         ...
17506     822
17507     822
17508     722
17509     822
17582    1223
Name: DATE_OF_INSPECT_090, Length: 8801, dtype: object

In [176]:
df_2.to_csv("nyc_bridges_19-24.csv", encoding="UTF-8")

In [169]:
import datetime

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [173]:
def convert_to_date(code):
    code = str(code)
    if len(code) == 3:
        month = code[:2].zfill(2)  # Ensure month is 2 digits
        year = '20' + code[2:]     # Assume year is in the 2000s
    elif len(code) == 4:
        month = code[:2]
        year = '20' + code[2:]
    else:
        raise ValueError(f"Invalid code length: {code}")

    # Return the date formatted as 'YYYY-MM-01' for correct datetime conversion
    return f"{year}-{month}-01"

# Apply the conversion and convert to datetime
df_2['DATE_OF_INSPECT_090'] = pd.to_datetime(df_2['DATE_OF_INSPECT_090'].apply(convert_to_date))

# Now format as '%m-%y' (month-year format)
df_2['DATE_OF_INSPECT_090'] = df_2['DATE_OF_INSPECT_090'].dt.strftime('%m-%y')

ValueError: time data "207-61-01" doesn't match format "%Y-%m-%d", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [172]:
df_2['DATE_OF_INSPECT_090'] = pd.to_datetime((df_2['DATE_OF_INSPECT_090'], format='%m%y').datetime.strftime('%m%y'))

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (<ipython-input-172-2e6735aa686a>, line 1)

In [143]:
df_2

,STATE_CODE_001,STRUCTURE_NUMBER_008,RECORD_TYPE_005A,ROUTE_PREFIX_005B,SERVICE_LEVEL_005C,ROUTE_NUMBER_005D,DIRECTION_005E,HIGHWAY_DISTRICT_002,COUNTY_CODE_003,PLACE_CODE_004,...,BRIDGE_LEN_IND_112,SCOUR_CRITICAL_113,FUTURE_ADT_114,YEAR_OF_FUTURE_ADT_115,MIN_NAV_CLR_MT_116,FED_AGENCY,SUBMITTED_BY,BRIDGE_CONDITION,LOWEST_RATING,DECK_AREA
4367,36,000000001055009,1,1,1,00495,0,N4,81,51000,...,Y,N,118735,2038,NaN,N,36,P,4,36434.3
4368,36,000000001055019,1,1,1,00495,0,N4,81,51000,...,Y,N,236498,2038,NaN,N,36,G,7,1988
4369,36,000000001055040,1,5,1,0907P,0,N3,61,51000,...,Y,3,93862,2038,NaN,N,36,F,5,2984.96
4370,36,000000001055070,1,8,0,00000,0,N4,81,51000,...,Y,N,0,0,NaN,N,36,F,5,3471.3
4371,36,000000001055089,1,1,1,00495,0,N4,81,51000,...,Y,8,147640,2038,NaN,N,36,F,5,4155.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17506,36,000000005525280,1,8,7,00000,0,N4,81,51000,...,Y,N,0,0,NaN,N,36,G,9,902.06
17507,36,000000005525290,1,8,8,00000,0,N4,81,51000,...,Y,N,0,0,NaN,N,36,G,9,3740.72
17508,36,000000005525291,1,8,7,00000,0,N4,81,51000,...,Y,N,0,0,NaN,N,36,G,9,1657.6
17509,36,000000005525292,1,8,8,00000,0,N4,81,51000,...,Y,N,0,0,NaN,N,36,G,9,4616.64
17582,36,000000007702320,1,5,0,00000,0,N1,5,51000,...,Y,N,70,2041,NaN,N,36,P,4,232.36

In [144]:
df_2["DATE_OF_INSPECT_090"].value_counts()

DATE_OF_INSPECT_090
1514764800000000000    279
1583020800000000000    250
1648771200000000000    228
1646092800000000000    226
1522540800000000000    211
                      ...
1551398400000000000      2
1614556800000000000      2
1488326400000000000      1
1438387200000000000      1
1706745600000000000      1
Name: count, Length: 83, dtype: int64

In [ ]:
, format="%m%y")